name: Terraform Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        run: |
          terraform --version
          echo "Terraform is installed!"

      - name: Build Terraform
        run: |
          terraform init
          terraform plan
          echo "Terraform build completed!"